# Generated by Django 6.0.7 on 2026-09-20 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена (₽)'),
        ),
    ]
